[tool.poetry]
name = "hautai_vault"
version = "4.0.0"
description = "A library providing means to interact with Hashicorp Vault"
authors = ["Fedor Eremeev <f.eremeev@haut.ai>", "Dmitrii Trofimov <d.trofimov@haut.ai>"]
repository = "https://pkgs.dev.azure.com/haut-ai/_packaging/haut-ai/pypi/upload"
packages = [{ include = "hautai_vault" }]
exclude = ["**/tests"]

[tool.poetry.dependencies]
python = "^3.9"
pydantic = "^2.5.2"
hvac = "^2.0.0"
pydantic-settings = "^2.1.0"

[tool.poetry.group.linters.dependencies]
ruff = "^0.1.7"
mypy = "^1.7.1"

[tool.poetry.group.shell.dependencies]
ipython = "^8.18.1"
rich = "^13.7.0"

[tool.poetry.group.tests.dependencies]
pytest = "^7.4.3"
pytest-cov = "^4.1.0"
pytest-xdist = "^3.5.0"

[tool.ruff]
line-length = 120

[[tool.poetry.source]]
name = "haut_ai"
url = "https://pkgs.dev.azure.com/haut-ai/_packaging/haut-ai/pypi/simple/"
priority = "supplemental"

[[tool.poetry.source]]
name = "haut_ai_publish"
url = "https://pkgs.dev.azure.com/haut-ai/_packaging/haut-ai/pypi/upload/"
priority = "supplemental"

[[tool.poetry.source]]
name = "PyPI"
priority = "primary"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.mypy]
plugins = [
  "pydantic.mypy"
]
