[tool.poetry]
name = "hautai_vault"
version = "2.0.3"
description = "A library providing means to interact with Hashicorp Vault"
authors = ["Vladislav Plisov <v.plisov@haut.ai>"]
repository = "https://pkgs.dev.azure.com/haut-ai/_packaging/haut-ai/pypi/upload"
packages = [
    {include = "hautai_vault"}
]
exclude = ["**/tests"]

[tool.poetry.dependencies]
python = "^3.9"
pydantic = {version = "^1.10.2", extras = ["dotenv"]}
hvac = "^1.0.2"

[tool.poetry.dev-dependencies]
isort = "^5.10.1"
black = "^22.3.0"
flake8 = "^4.0.1"
bandit = "^1.7.4"
flake8-bandit = "^3.0.0"
flake8-black = "^0.3.2"
flake8-bugbear = "^22.1.11"
flake8-comprehensions = "^3.8.0"
flake8-eradicate = "^1.2.0"
flake8-mutable = "^1.2.0"
flake8-print = "^4.0.0"
flake8-return = "^1.1.3"
flake8-simplify = "^0.14.5"
flake8-todos = "^0.1.5"
flake8-cognitive-complexity = "^0.1.0"
flake8-variables-names = "^0.0.4"
flake8-annotations-complexity = "^0.0.6"
flake8-length = "^0.2.2"
flake8-isort = "^4.1.1"
flake8-pie = "^0.15.0"
flake8-quotes = "^3.3.1"
flake8-string-format = "^0.3.0"
flake8-aaa = "^0.12.2"
ipython = "^8.2.0"

[tool.black]
line-length = 89
exclude = '''
(
  /(
      \.eggs
    | \.git
    | \.mypy_cache
    | \.tox
    | .venv
    | venv
    | build
    | dist
  )/
)
'''

[tool.isort]
use_parentheses = "True"
line_length = 89
skip = "build,.tox,venv,.venv"
profile = "black"

[[tool.poetry.source]]
name = "haut_ai"
url = "https://pkgs.dev.azure.com/haut-ai/_packaging/haut-ai%40Local/pypi/simple/"
secondary = true

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
