[tool.poetry]
name = "hautai_vault"
version = "0.1.0"
description = "A library providing means to interact with Hashicorp Vault"
authors = ["Vladislav Plisov <v.plisov@haut.ai>"]
repository = "https://pkgs.dev.azure.com/haut-ai/_packaging/haut-ai/pypi/upload"
packages = [
    {include = "hautai_vault"}
]
exclude = ["**/tests"]

[tool.poetry.dependencies]
python = ">=3.8,<3.11"
pydantic = "^1.9.0"
pydantic-vault = "^0.7.1"

[tool.poetry.dev-dependencies]
isort = "^5.10.1"
black = "^21.12b0"
flake8 = "^4.0.1"
bandit = "^1.7.1"

[tool.black]
line-length = 89
exclude = '''
(
  /(
      \.eggs
    | \.git
    | \.mypy_cache
    | \.tox
    | .venv
    | venv
    | build
    | dist
  )/
)
'''

[tool.isort]
use_parentheses = "True"
line_length = 89
skip = "build,.tox,venv,.venv"
profile = "black"

[[tool.poetry.source]]
name = "haut_ai"
url = "https://pkgs.dev.azure.com/haut-ai/_packaging/haut-ai%40Local/pypi/simple/"
secondary = true

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
