[tool.poetry]
name = "hautai_vault"
version = "3.0.0"
description = "A library providing means to interact with Hashicorp Vault"
authors = ["Fedor Eremeev <f.eremeev@haut.ai>", "Dmitrii Trofimov <d.trofimov@haut.ai>"]
repository = "https://pkgs.dev.azure.com/haut-ai/_packaging/haut-ai/pypi/upload"
packages = [{ include = "hautai_vault" }]
exclude = ["**/tests"]

[tool.poetry.dependencies]
python = "^3.9"
pydantic = "^2"
hvac = "^1.1.0"
pydantic-settings = "^2"

[tool.poetry.group.formatters.dependencies]
black = "^23.1.0"
isort = "^5.12.0"

[tool.poetry.group.linters.dependencies]
bandit = "^1.7.5"
flake8 = "<6"
flake8-aaa = "^0.12.2"
flake8-annotations-complexity = "^0.0.7"
flake8-bandit = "^4.1.1"
flake8-black = "^0.3.5"
flake8-bugbear = "^22.10.27"
flake8-cognitive-complexity = "^0.1.0"
flake8-comprehensions = "^3.10.1"
flake8-eradicate = "^1.4.0"
flake8-isort = "^5.0.3"
flake8-length = "^0.3.1"
flake8-mutable = "^1.2.0"
flake8-pie = "^0.16.0"
flake8-print = "^5.0.0"
flake8-quotes = "^3.3.1"
flake8-return = "^1.2.0"
flake8-simplify = "^0.19.3"
flake8-string-format = "^0.3.0"
flake8-todos = "^0.2.1"
flake8-variables-names = "^0.0.5"
mypy = "^1.1.1"

[tool.poetry.group.shell.dependencies]
ipython = "^8.11.0"
rich = "^13.3.2"
pytest = "^7.2.2"

[tool.poetry.group.tests.dependencies]
pytest = "^7.2.0"

[tool.black]
line-length = 89
exclude = '''
(
  /(
      \.eggs
    | \.git
    | \.mypy_cache
    | \.tox
    | .venv
    | venv
    | build
    | dist
  )/
)
'''

[tool.isort]
use_parentheses = "True"
line_length = 89
skip = "build,.tox,venv,.venv"
profile = "black"

[[tool.poetry.source]]
name = "haut_ai"
url = "https://pkgs.dev.azure.com/haut-ai/_packaging/haut-ai%40Local/pypi/simple/"
secondary = true

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
